name: Robot Framework UI Tests

on: [push]

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Robot Framework
        run: |
          pip install robotframework

      - name: Executar testes Robot Framework
        run: robot --outputdir results .

      - name: Upload resultados
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results/

      - name: Upload de relat√≥rios
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-framework-report
          path: results/
